import {sumOfModifiers, calcTotalValue} from "./calc_items_values.js";
import {state, updateState} from "./store.js";
const matchingSlots = {
	Head: null,
	Body: null,
	Arms: null,
	Legs: null,
};
const matchingSetBonus = {
	"Heavy Armor": {
		chosen: false,
		applied: false,
	},
	"Light Armor": {
		chosen: false,
		applied: false,
	},
};
const matchingItems = {
	"Heavy Armor": {
		"Iron Armor": ["iron"],
		"Iron Boots": ["iron"],
		"Iron Gauntlets": ["iron"],
		"Iron Helmet": ["iron"],
		"Iron Plate Armor": ["iron"],
		"Iron Plate Boots": ["iron"],
		"Iron Plate Gauntlets": ["iron"],
		"Iron Plate Helmet": ["iron"],
		"Banded Iron Armor": ["iron"],
		"Iron Spell Knight Armor": ["iron"],
		"Iron Spell Knight Boots": ["iron"],
		"Iron Spell Knight Gauntlets": ["iron"],
		"Iron Spell Knight Helmet": ["iron"],
		"Brawler's Iron Gauntlets": ["iron"],
		"Ancient Nord Armor": ["ancient_nord"],
		"Ancient Nord Boots": ["ancient_nord"],
		"Ancient Nord Gauntlets": ["ancient_nord"],
		"Ancient Nord Helmet": ["ancient_nord"],
		"Ancient Helmet of the Unburned":["ancient_nord"],
		"Bonemold Armor": ["bonemold"],
		"Bonemold Boots": ["bonemold"],
		"Bonemold Gauntlets": ["bonemold"],
		"Bonemold Helmet": ["bonemold"],
		"Bonemold Guard Armor": ["bonemold"],
		"Bonemold Pauldron Armor": ["bonemold"],
		"Improved Bonemold Armor": ["bonemold"],
		"Improved Bonemold Boots": ["bonemold"],
		"Improved Bonemold Gauntlets": ["bonemold"],
		"Improved Bonemold Helmet": ["bonemold"],
		"Dawnguard Heavy Armor": ["dawnguard_heavy"],
		"Dawnguard Heavy Boots": ["dawnguard_heavy"],
		"Dawnguard Heavy Gauntlets": ["dawnguard_heavy"],
		"Dawnguard Full Helmet": ["dawnguard_heavy"],
		"Steel Armor": ["steel"],
		"Steel Armor (Pauldron)": ["steel"],
		"Steel Shin Boots": ["steel"],
		"Steel Cuffed Boots": ["steel"],
		"Steel Imperial Gauntlets": ["steel"],
		"Steel Nordic Gauntlets": ["steel"],
		"Steel Helmet": ["steel"],
		"Steel Horned Helmet": ["steel"],
		"Ironhand Gauntlets": ["steel"],
		"Steel Soldier Armor": ["steel"],
		"Steel Soldier Boots": ["steel"],
		"Steel Soldier Gauntlets": ["steel"],
		"Steel Soldier Helmet": ["steel"],
		"Steel Spell Knight Armor": ["steel"],
		"Steel Spell Knight Boots": ["steel"],
		"Steel Spell Knight Gauntlets": ["steel"],
		"Steel Spell Knight Helmet": ["steel"],
		"Brawler's Steel Gauntlets": ["steel"],
		"Steel Plate Armor": ["steel_plate"],
		"Steel Plate Boots": ["steel_plate"],
		"Steel Plate Gauntlets": ["steel_plate"],
		"Steel Plate Helmet": ["steel_plate"],
		"Brawler's Steel Plate Gauntlets": ["steel_plate"],
		"Helm of Yngol": ["steel_plate", "ahzidal"],
		"Imperial Armor": ["imperial_heavy"],
		"Imperial Boots": ["imperial_heavy"],
		"Imperial Bracers": ["imperial_heavy"],
		"Imperial Helmet (full-face)": ["imperial_heavy"],
		"Imperial Helmet Officer's": ["imperial_heavy"],
		"Imperial Helmet": ["imperial_heavy"],
		"Chitin Heavy Armor": ["chitin_heavy"],
		"Chitin Heavy Boots": ["chitin_heavy"],
		"Chitin Heavy Gauntlets": ["chitin_heavy"],
		"Chitin Heavy Helmet": ["chitin_heavy"],
		"Dwarven Armor": ["dwarven_heavy"],
		"Dwarven Boots": ["dwarven_heavy"],
		"Dwarven Gauntlets": ["dwarven_heavy"],
		"Dwarven Helmet": ["dwarven_heavy"],
		"Dwarven Plate Armor": ["dwarven_heavy"],
		"Dwarven Plate Boots": ["dwarven_heavy"],
		"Visage of Mzund": ["dwarven_heavy"],
		"Brawler's Dwarven Gauntlets": ["dwarven_heavy"],
		"Nordic Carved Armor": ["nordic"],
		"Nordic Carved Boots": ["nordic"],
		"Nordic Carved Gauntlets": ["nordic"],
		"Nordic Carved Helmet": ["nordic"],
		"Orcish Armor": ["orcish_heavy"],
		"Orcish Boots": ["orcish_heavy"],
		"Orcish Gauntlets": ["orcish_heavy"],
		"Orcish Helmet": ["orcish_heavy"],
		"Orcish Plate Armor": ["orcish_heavy"],
		"Orcish Plate Boots": ["orcish_heavy"],
		"Orcish Plate Gauntlets": ["orcish_heavy"],
		"Orcish Plate Helmet": ["orcish_heavy"],
		"Brawler's Orcish Gauntlets": ["orcish_heavy"],
		"Ebony Armor": ["ebony"],
		"Ebony Boots": ["ebony"],
		"Ebony Gauntlets": ["ebony"],
		"Ebony Helmet": ["ebony"],
		"Ebony Mail": ["ebony"],
		"Ebony Plate Armor": ["ebony"],
		"Ebony Plate Boots": ["ebony"],
		"Ebony Plate Gauntlets": ["ebony"],
		"Ebony Plate Helmet": ["ebony"],
		"Ebony Spell Knight Armor": ["ebony"],
		"Ebony Spell Knight Boots": ["ebony"],
		"Ebony Spell Knight Gauntlets": ["ebony"],
		"Ebony Spell Knight Helmet": ["ebony"],
		"Brawler's Ebony Gauntlets": ["ebony"],
		"Stalhrim Armor": ["stalhrim_heavy"],
		"Stalhrim Boots": ["stalhrim_heavy"],
		"Stalhrim Gauntlets": ["stalhrim_heavy"],
		"Stalhrim Helmet": ["stalhrim_heavy"],
		"Stalhrim Fur Armor": ["stalhrim_heavy"],
		"Stalhrim Fur Boots": ["stalhrim_heavy"],
		"Stalhrim Fur Gauntlets": ["stalhrim_heavy"],
		"Stalhrim Fur Helmet": ["stalhrim_heavy"],
		"Dragonplate Armor": ["dragoplate"],
		"Dragonplate Boots": ["dragoplate"],
		"Dragonplate Gauntlets": ["dragoplate"],
		"Dragonplate Helmet": ["dragoplate"],
		"Dragonplate Insulated Cuirass": ["dragoplate"],
		"Dragonplate Insulated Boots": ["dragoplate"],
		"Dragonplate Insulated Gauntlets": ["dragoplate"],
		"Dragonplate Insulated Helmet": ["dragoplate"],
		"Brawler's Dragonplate Gauntlets": ["dragoplate"],
		"Daedric Armor": ["daedric_heavy"],
		"Daedric Boots": ["daedric_heavy"],
		"Daedric Gauntlets": ["daedric_heavy"],
		"Daedric Helmet": ["daedric_heavy"],
		"Daedric Plate Armor": ["daedric_heavy"],
		"Daedric Plate Helmet": ["daedric_heavy"],
		"Brawler's Daedric Gauntlets": ["daedric_heavy"],
		"Blades Armor": ["blades"],
		"Blades Boots": ["blades"],
		"Blades Gauntlets": ["blades"],
		"Blades Helmet": ["blades"],
		"Wolf Armor": ["wolf"],
		"Wolf Boots": ["wolf"],
		"Wolf Gauntlets": ["wolf"],
		"Wolf Helmet": ["wolf"],
		"Falmer Armor": ["falmer"],
		"Falmer Boots": ["falmer"],
		"Falmer Gauntlets": ["falmer"],
		"Falmer Helmet": ["falmer"],
		"Falmer Hardened Armor": ["falmer_hardened"],
		"Falmer Hardened Boots": ["falmer_hardened"],
		"Falmer Hardened Gauntlets": ["falmer_hardened"],
		"Falmer Hardened Helmet": ["falmer_hardened"],
		"Falmer Heavy Armor": ["falmer_heavy"],
		"Falmer Heavy Boots": ["falmer_heavy"],
		"Falmer Heavy Gauntlets": ["falmer_heavy"],
		"Falmer Heavy Helmet": ["falmer_heavy"],
		"Shellbug Helmet": ["falmer_heavy"],
		"Cuirass of the Crusader": ["crusader_heavy"],
		"Boots of the Crusader": ["crusader_heavy"],
		"Gauntlets of the Crusader": ["crusader_heavy"],
		"Helm of the Crusader": ["crusader_heavy"],
		"Ahzidal's Armor of Retribution": ["ahzidal"],
		"Ahzidal's Boots of Waterwalking": ["ahzidal"],
		"Ahzidal's Gauntlets of Warding": ["ahzidal"],
		"Ahzidal's Helm of Vision": ["ahzidal"],
		"Ahzidal": ["ahzidal"],
		"Golden Saint Armor": ["golden"],
		"Golden Saint Boots": ["golden"],
		"Golden Saint Gauntlets": ["golden"],
		"Golden Saint Helmet": ["golden"],
		"Madness Armor": ["madness"],
		"Madness Boots": ["madness"],
		"Madness Gauntlets": ["madness"],
		"Madness Helmet": ["madness"],
		"Indoril Armor": ["indoril"],
		"Indoril Boots": ["indoril"],
		"Indoril Gauntlets": ["indoril"],
		"Indoril Helmet": ["indoril"],
		"Her Hand Armor": ["her_hand"],
		"Her Hand Boots": ["her_hand"],
		"Her Hand Gauntlets": ["her_hand"],
		"Her Hand Helmet": ["her_hand"],
		"Silver Armor": ["silver"],
		"Silver Boots": ["silver"],
		"Silver Gauntlets": ["silver"],
		"Silver Helmet": ["silver"],
		"Imperial Dragon Armor": ["imperial_dragon"],
		"Imperial Dragon Boots": ["imperial_dragon"],
		"Imperial Dragon Gauntlets": ["imperial_dragon"],
		"Imperial Dragon Helmet": ["imperial_dragon"],
		"Storm-Bear Armor": ["storm_bear"],
		"Storm-Bear Boots": ["storm_bear"],
		"Storm-Bear Gauntlets": ["storm_bear"],
		"Storm-Bear Helmet": ["storm_bear"],
		"Vigil Corrupted Armor": ["vigil"],
		"Vigil Corrupted Boots": ["vigil"],
		"Vigil Corrupted Gauntlets": ["vigil"],
		"Vigil Corrupted Helmet": ["vigil"],
		"Vigil Corrupted Open Helmet": ["vigil"],
		"Vigil Enforcer Helmet": ["vigil"],
		"Vigil Enforcer Gauntlets": ["vigil"],
		"Vigil Enforcer Boots": ["vigil"],
		"Vigil Enforcer Armor": ["vigil"],
		"Vigil Silver Hand Helmet": ["vigil"],
		"Vigil Silver Hand Gauntlets": ["vigil"],
		"Vigil Silver Hand Boots": ["vigil"],
		"Vigil Silver Hand Armor": ["vigil"],
		"Vigil Veteran Helmet": ["vigil"],
		"Vigil Veteran Gauntlets": ["vigil"],
		"Vigil Veteran Boots": ["vigil"],
		"Vigil Veteran Armor": ["vigil"],
		"Vigil Corrupted Sashed Armor": ["vigil"],
		"Vigil Veteran Sashed Armor": ["vigil"],
		"Vigil Veteran Open Helmet": ["vigil"],
	},
	"Light Armor": {
		"Forsworn Armor": ["forsworn"],
		"Forsworn Boots": ["forsworn"],
		"Forsworn Gauntlets": ["forsworn"],
		"Forsworn Headdress": ["forsworn"],
		"Hide Armor": ["hide"],
		"Hide Boots": ["hide"],
		"Hide Bracers": ["hide"],
		"Hide Helmet": ["hide"],
		"Movarth's Boots": ["hide"],
		"Predator's Grace": ["hide"],
		"Brawler's Hide Bracers": ["hide"],
		"Leather Armor": ["leather"],
		"Leather Boots": ["leather"],
		"Leather Bracers": ["leather"],
		"Leather Helmet": ["leather"],
		"Leather Scout Armor": ["leather"],
		"Leather Scout Boots": ["leather"],
		"Leather Scout Gauntlets": ["leather"],
		"Leather Scout Helmet": ["leather"],
		"Brawler's Leather Bracers": ["leather"],
		"Dawnguard Armor": ["dawnguard_light"],
		"Dawnguard Boots": ["dawnguard_light"],
		"Dawnguard Gauntlets": ["dawnguard_light"],
		"Dawnguard Helmet": ["dawnguard_light"],
		"Chitin Armor": ["chitin_light"],
		"Chitin Boots": ["chitin_light"],
		"Chitin Bracers": ["chitin_light"],
		"Chitin Helmet": ["chitin_light"],
		"Redoran Watchman's Helmet": ["chitin_light"],
		"Elven Armor": ["elven"],
		"Elven Boots": ["elven"],
		"Elven Gauntlets": ["elven"],
		"Elven Helmet": ["elven"],
		"Elven Gilded Armor": ["elven"],
		"Elven Hunter Armor": ["elven"],
		"Elven Hunter Boots": ["elven"],
		"Elven Hunter Gauntlets": ["elven"],
		"Elven Light Armor": ["elven"],
		"Elven Light Boots": ["elven"],
		"Elven Light Gauntlets": ["elven"],
		"Elven Light Helmet": ["elven"],
		"Brawler's Elven Gauntlets": ["elven"],
		"Scaled Armor": ["scaled"],
		"Scaled Horn Armor": ["scaled"],
		"Scaled Boots": ["scaled"],
		"Scaled Bracers": ["scaled"],
		"Scaled Helmet": ["scaled"],
		"Brawler's Scaled Bracers": ["scaled"],
		"Thieves Guild Armor": ["thief"],
		"Thieves Guild Boots": ["thief"],
		"Thieves Guild Gloves": ["thief"],
		"Thieves Guild Hood": ["thief"],
		"Improved Thieves Guild Armor": ["thief"],
		"Improved Thieves Guild Boots": ["thief"],
		"Improved Thieves Guild Gloves": ["thief"],
		"Improved Thieves Guild Hood": ["thief"],
		"Stalhrim Light Armor": ["stalhrim_light"],
		"Stalhrim Light Boots": ["stalhrim_light"],
		"Stalhrim Light Bracers": ["stalhrim_light"],
		"Stalhrim Light Helmet": ["stalhrim_light"],
		"Glass Armor": ["glass"],
		"Glass Boots": ["glass"],
		"Glass Gauntlets": ["glass"],
		"Glass Helmet": ["glass"],
		"Brawler's Glass Gauntlets": ["glass"],
		"Dragonscale Armor": ["dragonscale"],
		"Dragonscale Boots": ["dragonscale"],
		"Dragonscale Gauntlets": ["dragonscale"],
		"Dragonscale Helmet": ["dragonscale"],
		"Studded Dragonscale Armor": ["dragonscale"],
		"Studded Dragonscale Boots": ["dragonscale"],
		"Studded Dragonscale Gauntlets": ["dragonscale"],
		"Studded Dragonscale Helmet": ["dragonscale"],
		"Brawler's Dragonscale Gauntlets": ["dragonscale"],
		"Imperial Light Armor": ["imperial_light"],
		"Imperial Light Boots": ["imperial_light"],
		"Imperial Light Bracers": ["imperial_light"],
		"Imperial Light Helmet": ["imperial_light"],
		"Studded Imperial Armor": ["imperial_light"],
		"Worn Shrouded Armor": ["shrouded"],
		"Worn Shrouded Boots": ["shrouded"],
		"Worn Shrouded Cowl": ["shrouded"],
		"Worn Shrouded Gloves": ["shrouded"],
		"Ancient Shrouded Armor": ["shrouded"],
		"Ancient Shrouded Boots": ["shrouded"],
		"Ancient Shrouded Cowl": ["shrouded"],
		"Ancient Shrouded Gloves": ["shrouded"],
		"Shrouded Armor": ["shrouded"],
		"Shrouded Boots": ["shrouded"],
		"Shrouded Gloves": ["shrouded"],
		"Shrouded Hood": ["shrouded"],
		"Tumblerbane Gloves": ["shrouded"],
		"Penitus Oculatus Armor": ["penitus"],
		"Penitus Oculatus Boots": ["penitus"],
		"Penitus Oculatus Bracers": ["penitus"],
		"Penitus Oculatus Helmet": ["penitus"],
		"Morag Tong Armor": ["morag"],
		"Morag Tong Boots": ["morag"],
		"Morag Tong Bracers": ["morag"],
		"Morag Tong Helmet": ["morag"],
		"Skaal Boots": ["skaal"],
		"Skaal Coat": ["skaal"],
		"Skaal Gloves": ["skaal"],
		"Skaal Hat": ["skaal"],
		"Fur Boots": ["stormcloak"],
		"Fur Gauntlets": ["stormcloak"],
		"Gloves of the Pugilist": ["stormcloak"],
		"Stormcloak Cuirass": ["stormcloak"],
		"Stormcloak Helmet": ["stormcloak"],
		"Stormcloak Officer Armor": ["officer"],
		"Stormcloak Officer Boots": ["officer"],
		"Stormcloak Officer Bracers": ["officer"],
		"Stormcloak Officer Helmet": ["officer"],
		"Ancient Falmer Boots": ["ancient_falmer"],
		"Ancient Falmer Crown": ["ancient_falmer"],
		"Ancient Falmer Cuirass": ["ancient_falmer"],
		"Ancient Falmer Gauntlets": ["ancient_falmer"],
		"Reforged Cuirass of the Crusader": ["crusader_light"],
		"Reforged Boots of the Crusader": ["crusader_light"],
		"Reforged Gauntlets of the Crusader": ["crusader_light"],
		"Reforged Helm of the Crusader": ["crusader_light"],
		"Nightingale Armor": ["nightingale"],
		"Nightingale Boots": ["nightingale"],
		"Nightingale Gloves": ["nightingale"],
		"Nightingale Hood": ["nightingale"],
		"Deathbrand Armor": ["deathbrand"],
		"Deathbrand Boots": ["deathbrand"],
		"Deathbrand Gauntlets": ["deathbrand"],
		"Deathbrand Helm": ["deathbrand"],
		"Guild Master's Armor": ["guild_master"],
		"Guild Master's Boots": ["guild_master"],
		"Guild Master's Gloves": ["guild_master"],
		"Guild Master's Hood": ["guild_master"],
		"Armor of the Old Gods": ["old_gods"],
		"Boots of the Old Gods": ["old_gods"],
		"Gauntlets of the Old Gods": ["old_gods"],
		"Helmet of the Old Gods": ["old_gods"],
		"Remnant Agent Armor": ["remnant"],
		"Remnant Agent Boots": ["remnant"],
		"Remnant Agent Gloves": ["remnant"],
		"Remnant Agent Hood": ["remnant"],
		"Remnant Armor": ["remnant"],
		"Remnant Boots": ["remnant"],
		"Remnant Gloves": ["remnant"],
		"Remnant Hood": ["remnant"],
		"Dark Seducer Armor": ["seducer"],
		"Dark Seducer Boots": ["seducer"],
		"Dark Seducer Gauntlets": ["seducer"],
		"Dark Seducer Helmet": ["seducer"],
		"Amber Armor": ["amber"],
		"Amber Boots": ["amber"],
		"Amber Gauntlets": ["amber"],
		"Amber Helmet": ["amber"],
		"Orcish Scaled Armor": ["orcish_light"],
		"Orcish Scaled Boots": ["orcish_light"],
		"Orcish Scaled Gauntlets": ["orcish_light"],
		"Orcish Scaled Helmet": ["orcish_light"],
		"Dwarven Mail Armor": ["dwarven_light"],
		"Dwarven Mail Boots": ["dwarven_light"],
		"Dwarven Mail Gauntlets": ["dwarven_light"],
		"Dwarven Mail Helmet": ["dwarven_light"],
		"Boiled Netch Leather Armor": ["netch"],
		"Boiled Netch Leather Helmet": ["netch"],
		"Boots of Blinding Speed": ["netch"],
		"Netch Leather Armor": ["netch"],
		"Netch Leather Boots": ["netch"],
		"Netch Leather Bracers": ["netch"],
		"Netch Leather Helmet": ["netch"],
		"Painted Netch Leather Armor": ["netch"],
		"Painted Netch Leather Boots": ["netch"],
		"Painted Netch Leather Bracers": ["netch"],
		"Painted Netch Leather Helmet": ["netch"],
		"Shadowed Boiled Netch Leather Armor": ["netch"],
		"Shadowed Boiled Netch Leather Helmet": ["netch"],
		"Shadowed Netch Leather Armor": ["netch"],
		"Shadowed Netch Leather Boots": ["netch"],
		"Shadowed Netch Leather Bracers": ["netch"],
		"Shadowed Netch Leather Helmet": ["netch"],
	},
};
function checkMatchingSetArmor(name, slot, armorType, sign) {
	if (armorType !== "Heavy" && armorType !== "Light") return;
	if (!(slot in matchingSlots)) return;
	armorType += " Armor";
	if (sign === 1) {
		updateState(s => { if (!s.equipment.equippedMatchingItems.includes(name)) s.equipment.equippedMatchingItems.push(name); });
		matchingSlots[slot] = matchingItems[armorType][name];
		setMatchingSetBonus(armorType, sign);
	} else if (sign === -1) {
		setMatchingSetBonus(armorType, sign);
		updateState(s => { s.equipment.equippedMatchingItems = s.equipment.equippedMatchingItems.filter(item => item !== name); });
		matchingSlots[slot] = null;
	}
}
function checkMatchingSetPerk(perkName, bool, skillTree) {
	if (perkName !== "Matching Set") return;
	const skill = skillTree ? skillTree : state.skills.currentSkillTree;
	const bonus = matchingSetBonus[skill];
	if (bool) {
		bonus.chosen = true;
		setMatchingSetBonus(skill, 1);
	} else {
		setMatchingSetBonus(skill, -1);
		bonus.chosen = false;
	}
}
function setMatchingSetBonus(armorType, sign) {
	if (state.equipment.equippedMatchingItems.length !== 4) return;
	const bonus = matchingSetBonus[armorType];
	if (!bonus.chosen) return;
	if (sign === 1) {
		const map = {};
		let count = 0;
		for (const i of Object.values(matchingSlots).flat()) {
			count = (map[i] || 0) + 1;
			if (count === 4) break;
			map[i] = count;
		}
		if (count === 4) {
			sumOfModifiers[armorType].sameSet += sign * .25;
			calcTotalValue();
			bonus.applied = true;
		}
	} else if (sign === -1) {
		sumOfModifiers[armorType].sameSet += sign * .25;
		calcTotalValue();
		bonus.applied = false;
	}
}
export {checkMatchingSetArmor, checkMatchingSetPerk};